"""
Utilities for parsing AI-generated quizzes.
"""

import re


def parse_quiz(quiz_text: str) -> list[dict]:
    """
    Parse a structured AI-generated quiz.

    Args:
        quiz_text: Raw quiz text generated by the AI.

    Returns:
        A list of parsed quiz questions.
    """

    pattern = re.compile(
        r"QUESTION\s+\d+:\s*"
        r"(.*?)\n\s*"
        r"A\)\s*(.*?)\n\s*"
        r"B\)\s*(.*?)\n\s*"
        r"C\)\s*(.*?)\n\s*"
        r"D\)\s*(.*?)\n\s*"
        r"ANSWER:\s*([ABCD])\s*"
        r"EXPLANATION:\s*(.*?)(?=\n\s*QUESTION\s+\d+:|\Z)",
        re.DOTALL | re.IGNORECASE,
    )

    matches = pattern.findall(quiz_text)

    questions = []

    for match in matches:

        question, option_a, option_b, option_c, option_d, answer, explanation = match

        questions.append(
            {
                "question": question.strip(),
                "options": {
                    "A": option_a.strip(),
                    "B": option_b.strip(),
                    "C": option_c.strip(),
                    "D": option_d.strip(),
                },
                "answer": answer.upper().strip(),
                "explanation": explanation.strip(),
            }
        )

    return questions